version: '3.3'

services:
    mysql:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306

    redis:
        image: redis:6
        command: redis-server
        ports:
            - 6379:6379
