sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        products:
            routes:
                list: app.get_products
                detail: app.get_product
    field_type_options:
        selection:
            product_selection:
                default_type: list_overlay
                resource_key: products
                types:
                    list_overlay:
                        adapter: table
                        list_key: products
                        display_properties:
                            - name
                        icon: fa-dollar
                        label: 'app.products'
                        overlay_title: 'app.products'